### ISSUE TITLE
Add new YAML logo to the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/Yoshitha-Site#105]
Add new YAML logo after the bootstrap logo in the readme.md file

**Comment by Rishav1707** [comment]
Is there any link to the YAML logo or which logo to add to the readme file?

**Comment by YoshithaRathnayake** [comment]
> Is there any link to the YAML logo or which logo to add to the readme file?

Please look at the my other repositories and insert the logo which is located in them

**Comment by Rishav1707** [comment]
Ok
